### ISSUE TITLE
Creating simple-commerce-nav

### ISSUE THREAD

**Issue by HazemMohamed252** [thoughtco/simple-commerce-nav#1]
After run the command i got this issue : Call to a member function showUrl() on null

**Comment by ryanmitchell** [comment]
Have you installed simple commerce?

**Comment by HazemMohamed252** [comment]
Yes and i run this command : composer require thoughtco/simple-commerce-nav
But suddenly i got the previous error due to showUrl() in the layout view

**Comment by ryanmitchell** [comment]
You need to install the simple commerce add on first 😀

**Comment by HazemMohamed252** [comment]
How to install it please

**Comment by ryanmitchell** [comment]
https://statamic.com/addons/double-three-digital/simple-commerce
